-- AlterEnum
ALTER TYPE "JobEventType" ADD VALUE 'WORKTREE_CREATED';
ALTER TYPE "JobEventType" ADD VALUE 'WORKTREE_CREATION_FAILED';
ALTER TYPE "JobEventType" ADD VALUE 'WORKTREE_REMOVED';
ALTER TYPE "JobEventType" ADD VALUE 'WORKTREE_REMOVAL_FAILED';
ALTER TYPE "JobEventType" ADD VALUE 'DEPENDENCY_INSTALL_STARTED';
ALTER TYPE "JobEventType" ADD VALUE 'DEPENDENCY_INSTALL_COMPLETED';
ALTER TYPE "JobEventType" ADD VALUE 'DEPENDENCY_INSTALL_FAILED';

-- AlterTable
ALTER TABLE "repositories" ADD COLUMN     "install_command" TEXT;
