ALTER TABLE "repositories"
ADD COLUMN "jira_base_url" TEXT,
ADD COLUMN "jira_project_key" TEXT,
ADD COLUMN "jira_issue_type" TEXT;

ALTER TYPE "JobEventType" ADD VALUE 'JIRA_TICKET_CREATED';
ALTER TYPE "JobEventType" ADD VALUE 'JIRA_TICKET_CREATION_FAILED';
ALTER TYPE "JobEventType" ADD VALUE 'JIRA_TICKET_CREATION_SKIPPED';
