ALTER TYPE "JobEventType" ADD VALUE 'REPOSITORY_CHECKOUT_VALIDATION_STARTED';
ALTER TYPE "JobEventType" ADD VALUE 'REPOSITORY_CHECKOUT_VALIDATED';
ALTER TYPE "JobEventType" ADD VALUE 'JOB_BLOCKED';

ALTER TABLE "repositories" ADD COLUMN "local_path" TEXT;
