ALTER TYPE "JobEventType" ADD VALUE 'PR_CHECKS_PENDING';
ALTER TYPE "JobEventType" ADD VALUE 'PR_CHECKS_PASSED';
ALTER TYPE "JobEventType" ADD VALUE 'PR_CHECKS_FAILED';
ALTER TYPE "JobEventType" ADD VALUE 'PR_MERGED';
ALTER TYPE "JobEventType" ADD VALUE 'PR_CLOSED';
