ALTER TYPE "JobStatus" ADD VALUE 'READY_FOR_CODEX';
ALTER TYPE "JobStatus" ADD VALUE 'CODEX_APPROVED';

ALTER TYPE "RunStatus" ADD VALUE 'READY_FOR_CODEX';

ALTER TYPE "JobEventType" ADD VALUE 'CODEX_APPROVAL_REQUIRED';
ALTER TYPE "JobEventType" ADD VALUE 'CODEX_APPROVAL_GRANTED';
