ALTER TYPE "JobEventType" ADD VALUE 'PR_CREATION_STARTED';
ALTER TYPE "JobEventType" ADD VALUE 'WORK_BRANCH_PUSHED';
ALTER TYPE "JobEventType" ADD VALUE 'PR_CREATED';
ALTER TYPE "JobEventType" ADD VALUE 'PR_CREATION_FAILED';
